public enum RoomType {
    SUITE,
    FAMILY_ROOM,
    STUDIO,
    PRESIDENTIAL_SUITE,
    EXECUTIVE_SUITE,
    BRIDAL_SUITE,
    HONEYMOON_SUITE,
    STANDARD,
    PENTHOUSE,
    DELUXE,
    STANDARD_SUITE;
}
